/* 
  This file was generated by KreMLin <https://github.com/FStarLang/kremlin>
  KreMLin invocation: krml -verbose -d reachability -I . -I includes -tmpdir /Users/syuan/GoogleDrive/PhD/FstarCode/LCTES2021/riotboot/out/sources -no-prefix FStarFiles /Users/syuan/GoogleDrive/PhD/FstarCode/LCTES2021/riotboot/out/out.krml -ccopt -O0 main.c -add-include "kremlin/internal/compat.h" -bundle LowStar.*,Prims -bundle FStar.* -o /Users/syuan/GoogleDrive/PhD/FstarCode/LCTES2021/riotboot/out/LowKernel
  F* version: cfb65605
  KreMLin version: 03ccd42f
 */

#include "ChooseImage.h"

bool ChooseImage_choose_image_aux1(RbComm_rb_hdr_t img)
{
  RbComm_rb_hdr_t tb = img;
  bool b = Lowhdr_rb_hdr_validate(&tb);
  return b;
}

FStar_Pervasives_Native_option__uint32_t
ChooseImage_choose_image_aux(
  RbComm_rb_hdr_t *images,
  Prims_int len,
  FStar_Pervasives_Native_option__RbComm_rb_hdr_t opt
)
{
  if (len == (krml_checked_int_t)0)
  {
    RbComm_rb_hdr_t img = images[FStar_UInt32_uint_to_t(len)];
    bool b = ChooseImage_choose_image_aux1(img);
    if (b == true)
      if (opt.tag == FStar_Pervasives_Native_Some)
      {
        RbComm_rb_hdr_t t = opt.v;
        if (img.version <= t.version)
          return
            (
              (FStar_Pervasives_Native_option__uint32_t){
                .tag = FStar_Pervasives_Native_Some,
                .v = t.start_addr
              }
            );
        else
          return
            (
              (FStar_Pervasives_Native_option__uint32_t){
                .tag = FStar_Pervasives_Native_Some,
                .v = img.start_addr
              }
            );
      }
      else if (opt.tag == FStar_Pervasives_Native_None)
        return ((FStar_Pervasives_Native_option__uint32_t){ .tag = FStar_Pervasives_Native_None });
      else
      {
        KRML_HOST_EPRINTF("KreMLin abort at %s:%d\n%s\n",
          __FILE__,
          __LINE__,
          "unreachable (pattern matches are exhaustive in F*)");
        KRML_HOST_EXIT(255U);
      }
    else if (opt.tag == FStar_Pervasives_Native_Some)
    {
      RbComm_rb_hdr_t t = opt.v;
      return
        (
          (FStar_Pervasives_Native_option__uint32_t){
            .tag = FStar_Pervasives_Native_Some,
            .v = t.start_addr
          }
        );
    }
    else if (opt.tag == FStar_Pervasives_Native_None)
      return ((FStar_Pervasives_Native_option__uint32_t){ .tag = FStar_Pervasives_Native_None });
    else
    {
      KRML_HOST_EPRINTF("KreMLin abort at %s:%d\n%s\n",
        __FILE__,
        __LINE__,
        "unreachable (pattern matches are exhaustive in F*)");
      KRML_HOST_EXIT(255U);
    }
  }
  else
  {
    RbComm_rb_hdr_t img = images[FStar_UInt32_uint_to_t(len)];
    bool b = ChooseImage_choose_image_aux1(img);
    if (b == true)
      if (opt.tag == FStar_Pervasives_Native_None)
        return
          ChooseImage_choose_image_aux(images,
            Prims_op_Subtraction(len, (krml_checked_int_t)1),
            (
              (FStar_Pervasives_Native_option__RbComm_rb_hdr_t){
                .tag = FStar_Pervasives_Native_Some,
                .v = img
              }
            ));
      else if (opt.tag == FStar_Pervasives_Native_Some)
      {
        RbComm_rb_hdr_t t = opt.v;
        if (img.version <= t.version)
          return
            ChooseImage_choose_image_aux(images,
              Prims_op_Subtraction(len, (krml_checked_int_t)1),
              opt);
        else
          return
            ChooseImage_choose_image_aux(images,
              Prims_op_Subtraction(len, (krml_checked_int_t)1),
              (
                (FStar_Pervasives_Native_option__RbComm_rb_hdr_t){
                  .tag = FStar_Pervasives_Native_Some,
                  .v = img
                }
              ));
      }
      else
      {
        KRML_HOST_EPRINTF("KreMLin abort at %s:%d\n%s\n",
          __FILE__,
          __LINE__,
          "unreachable (pattern matches are exhaustive in F*)");
        KRML_HOST_EXIT(255U);
      }
    else
      return
        ChooseImage_choose_image_aux(images,
          Prims_op_Subtraction(len, (krml_checked_int_t)1),
          opt);
  }
}

FStar_Pervasives_Native_option__uint32_t ChooseImage_choose_image(RbComm_rb_hdr_t *images)
{
  return
    ChooseImage_choose_image_aux(images,
      Prims_op_Subtraction(RbComm_rb_slot_numof, (krml_checked_int_t)1),
      ((FStar_Pervasives_Native_option__RbComm_rb_hdr_t){ .tag = FStar_Pervasives_Native_None }));
}

