/* 
  This file was generated by KreMLin <https://github.com/FStarLang/kremlin>
  KreMLin invocation: krml -verbose -d reachability -I . -I includes -tmpdir /Users/syuan/GoogleDrive/PhD/FstarCode/LCTES2021/riotboot/out/sources -no-prefix FStarFiles /Users/syuan/GoogleDrive/PhD/FstarCode/LCTES2021/riotboot/out/out.krml -ccopt -O0 main.c -add-include "kremlin/internal/compat.h" -bundle LowStar.*,Prims -bundle FStar.* -o /Users/syuan/GoogleDrive/PhD/FstarCode/LCTES2021/riotboot/out/LowKernel
  F* version: cfb65605
  KreMLin version: 03ccd42f
 */

#ifndef __ChooseImage_H
#define __ChooseImage_H
#include "kremlin/internal/compat.h"
#include "kremlib.h"


#include "RbComm.h"
#include "LowStar_Prims.h"
#include "Lowhdr.h"
#include "FStar.h"

bool ChooseImage_choose_image_aux1(RbComm_rb_hdr_t img);

#define FStar_Pervasives_Native_None 0
#define FStar_Pervasives_Native_Some 1

typedef uint8_t FStar_Pervasives_Native_option__uint32_t_tags;

typedef struct FStar_Pervasives_Native_option__uint32_t_s
{
  FStar_Pervasives_Native_option__uint32_t_tags tag;
  uint32_t v;
}
FStar_Pervasives_Native_option__uint32_t;

typedef struct FStar_Pervasives_Native_option__RbComm_rb_hdr_t_s
{
  FStar_Pervasives_Native_option__uint32_t_tags tag;
  RbComm_rb_hdr_t v;
}
FStar_Pervasives_Native_option__RbComm_rb_hdr_t;

FStar_Pervasives_Native_option__uint32_t
ChooseImage_choose_image_aux(
  RbComm_rb_hdr_t *images,
  Prims_int len,
  FStar_Pervasives_Native_option__RbComm_rb_hdr_t opt
);

FStar_Pervasives_Native_option__uint32_t ChooseImage_choose_image(RbComm_rb_hdr_t *images);


#define __ChooseImage_H_DEFINED
#endif
