/* 
  This file was generated by KreMLin <https://github.com/FStarLang/kremlin>
  KreMLin invocation: krml -verbose -d reachability -I . -I includes -tmpdir /Users/syuan/GoogleDrive/PhD/FstarCode/LCTES2021/riotboot/out/sources -no-prefix FStarFiles /Users/syuan/GoogleDrive/PhD/FstarCode/LCTES2021/riotboot/out/out.krml -ccopt -O0 main.c -add-include "kremlin/internal/compat.h" -bundle LowStar.*,Prims -bundle FStar.* -o /Users/syuan/GoogleDrive/PhD/FstarCode/LCTES2021/riotboot/out/LowKernel
  F* version: cfb65605
  KreMLin version: 03ccd42f
 */

#ifndef __LowFletcher32_H
#define __LowFletcher32_H
#include "kremlin/internal/compat.h"
#include "kremlib.h"


#include "FStar.h"

typedef struct K___uint32_t_uint32_t_s
{
  uint32_t fst;
  uint32_t snd;
}
K___uint32_t_uint32_t;

K___uint32_t_uint32_t
LowFletcher32_dowhile(uint32_t t, uint32_t tlen, uint16_t *d, uint32_t s1, uint32_t s2);

K___uint32_t_uint32_t
LowFletcher32_while_t(uint16_t words, uint16_t *data, uint32_t s1, uint32_t s2);

uint32_t LowFletcher32_fletcher32(uint16_t words, uint16_t *data);


#define __LowFletcher32_H_DEFINED
#endif
