/* 
  This file was generated by KreMLin <https://github.com/FStarLang/kremlin>
  KreMLin invocation: krml -verbose -d reachability -I . -I includes -tmpdir /Users/syuan/GoogleDrive/PhD/FstarCode/LCTES2021/riotboot/out/sources -no-prefix FStarFiles /Users/syuan/GoogleDrive/PhD/FstarCode/LCTES2021/riotboot/out/out.krml -ccopt -O0 main.c -add-include "kremlin/internal/compat.h" -bundle LowStar.*,Prims -bundle FStar.* -o /Users/syuan/GoogleDrive/PhD/FstarCode/LCTES2021/riotboot/out/LowKernel
  F* version: cfb65605
  KreMLin version: 03ccd42f
 */

#ifndef __Lowhdr_H
#define __Lowhdr_H
#include "kremlin/internal/compat.h"
#include "kremlib.h"


#include "LowFletcher32.h"
#include "RbComm.h"

extern uint32_t Lowhdr_rm;

extern uint16_t Lowhdr_offset_chksum;

void Lowhdr_rb_hdr_t2uint16_t(RbComm_rb_hdr_t s, uint16_t *d);

uint32_t Lowhdr_rb_hdr_checksum_aux(RbComm_rb_hdr_t h);

uint32_t Lowhdr_rb_hdr_checksum(RbComm_rb_hdr_t *b);

bool Lowhdr_rb_hdr_validate(RbComm_rb_hdr_t *h);


#define __Lowhdr_H_DEFINED
#endif
